language: node_js
node_js: "8"
cache:
  directories:
    - "node_modules"
addons:
  apt:
    packages:
      - ghostscript
before_deploy:
  - npm run dist
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_key
  local_dir: dist
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|release-.*)$
